New deploy file

diff --git a/Demo_Project/.github/workflows/deploy.yml b/Demo_Project/.github/workflows/deploy.yml
--- a/Demo_Project/.github/workflows/deploy.yml
+++ b/Demo_Project/.github/workflows/deploy.yml
@@ -21,8 +21,11 @@ jobs:
 
       - name: Authenticate with Salesforce Org
         run: |
-          sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername -a DevHub
-          sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} -a MyOrg
+          echo "Authenticating with Salesforce Org..."
+          sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername -a DevHub || { echo "Authentication failed."; exit 1; }
+          sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} -a MyOrg || { echo "Authentication failed."; exit 1; }
 
       - name: Deploy to Salesforce Org
-        run: sfdx force:source:deploy -p force-app/main/default
+        run: |
+          echo "Deploying to Salesforce Org..."
+          sfdx force:source:deploy -p force-app/main/default || { echo "Deployment failed."; exit 1; }
